# ============================================================
#  NutriBot — Interactive .env Setup Script
#  Run this ONCE to create your .env file with real credentials.
#  Usage:  powershell -ExecutionPolicy Bypass -File setup_env.ps1
# ============================================================

Write-Host ""
Write-Host "============================================================" -ForegroundColor Cyan
Write-Host "  NutriBot — IBM Watsonx.ai Credential Setup" -ForegroundColor Cyan
Write-Host "============================================================" -ForegroundColor Cyan
Write-Host ""
Write-Host "You will need:" -ForegroundColor Yellow
Write-Host "  1. IBM Cloud API Key  -> https://cloud.ibm.com/iam/apikeys" -ForegroundColor Yellow
Write-Host "  2. Watsonx Project ID -> https://dataplatform.cloud.ibm.com" -ForegroundColor Yellow
Write-Host "     (Open your project -> Manage tab -> copy Project ID)" -ForegroundColor Yellow
Write-Host ""

# --- IBM API Key ---
do {
    $apiKey = Read-Host "Paste your IBM Cloud API Key"
    $apiKey = $apiKey.Trim()
    if (-not $apiKey) { Write-Host "  API key cannot be empty. Try again." -ForegroundColor Red }
} while (-not $apiKey)

# --- Project ID ---
do {
    $projectId = Read-Host "Paste your Watsonx Project ID"
    $projectId = $projectId.Trim()
    if (-not $projectId) { Write-Host "  Project ID cannot be empty. Try again." -ForegroundColor Red }
} while (-not $projectId)

# --- Region ---
Write-Host ""
Write-Host "Select your IBM Cloud region:" -ForegroundColor Cyan
Write-Host "  [1] us-south  (Dallas)    -- most common" -ForegroundColor White
Write-Host "  [2] eu-de     (Frankfurt)" -ForegroundColor White
Write-Host "  [3] eu-gb     (London)" -ForegroundColor White
Write-Host "  [4] jp-tok    (Tokyo)" -ForegroundColor White
Write-Host "  [5] au-syd    (Sydney)" -ForegroundColor White

$regionChoice = Read-Host "Enter 1-5 (press Enter for us-south)"
switch ($regionChoice) {
    "2" { $watsonxUrl = "https://eu-de.ml.cloud.ibm.com" }
    "3" { $watsonxUrl = "https://eu-gb.ml.cloud.ibm.com" }
    "4" { $watsonxUrl = "https://jp-tok.ml.cloud.ibm.com" }
    "5" { $watsonxUrl = "https://au-syd.ml.cloud.ibm.com" }
    default { $watsonxUrl = "https://us-south.ml.cloud.ibm.com" }
}

# --- Secret key (auto-generated) ---
$secretKey = -join ((65..90) + (97..122) + (48..57) | Get-Random -Count 40 | ForEach-Object { [char]$_ })

# --- Write .env ---
$envPath = Join-Path $PSScriptRoot ".env"

$envContent = @"
# ============================================================
#  NutriBot — IBM Watsonx.ai Credentials  (DO NOT COMMIT)
#  Generated by setup_env.ps1
# ============================================================

IBM_API_KEY=$apiKey
IBM_WATSONX_URL=$watsonxUrl
IBM_WATSONX_PROJECT_ID=$projectId

WATSONX_MODEL_ID=meta-llama/llama-3-3-70b-instruct

FLASK_SECRET_KEY=$secretKey
FLASK_DEBUG=False
FLASK_PORT=5000
"@

Set-Content -Path $envPath -Value $envContent -Encoding UTF8

Write-Host ""
Write-Host "============================================================" -ForegroundColor Green
Write-Host "  .env file created successfully!" -ForegroundColor Green
Write-Host "============================================================" -ForegroundColor Green
Write-Host ""
Write-Host "  Region : $watsonxUrl" -ForegroundColor White
Write-Host "  API Key: $($apiKey.Substring(0, [Math]::Min(8, $apiKey.Length)))..." -ForegroundColor White
Write-Host "  Project: $($projectId.Substring(0, [Math]::Min(8, $projectId.Length)))..." -ForegroundColor White
Write-Host ""
Write-Host "Now start the app:" -ForegroundColor Cyan
Write-Host "  python app.py" -ForegroundColor Yellow
Write-Host ""
